### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by simonsmiley** [rajeevs1992/mailmancli#1]
Hi there,
I'm helping in developing mailman and thus also mailmanclient. It's very confusing for people that you have a mailmancli project, and it shows up quite high when searching for mailmanclient through google. While I don't mind you having your own project, we end up with people requesting assistance after they follow instruction from your repository.

I'm not asking you to shut it down, but it would be helpful if you pointed out that this is not an official peace of software. It would be helpful to have that in the github repository and also over at readthedocs.

**Comment by rajeevs1992** [comment]
Hi Simon,

I have added a disclaimer at the top of the readme mentioning the same. Sorry for the trouble.
